#deployment & service in 1 file
#-------------------
#deployment
#by right, we should use "stateful" for database, 
#but to keep it simply we use deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo #common label for deployments
spec:
  replicas: 1  # how many pods we want to create using blueprint (template)
  selector:  # identify resources
    matchLabels: #match all pods with label "app:mongo"
      app: mongo
  template: #blueprint for pods, config of pods within config of deployment
    metadata:
      labels: #common label for all pods
        app: mongo
    spec:
      containers:
      - name: mongodb #create pods with mongo:5.0 image
        image: mongo:5.0 #can replace with a newer tag
        ports:
        - containerPort: 27017 #https://hub.docker.com/_/mongo
        env: #set up username and password to access mongodb
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
--- # we can have multiple YAML configs in 1 file, --- separates the configs
# internal service
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo #label of pods
  #request comes in, first it goes to port 27017, which is mongo service
  #then it goes to port 27017, which is target port
  #from target port 27017, it reaches container port 27017, which is the pod
  ports:
    - protocol: TCP
      port: 27017 # can be anything, normally use the same value as targetPort
      targetPort: 27017 #same as container port
